### ISSUE TITLE
wrong symbol version for _Unwind_GetIPInfo

### ISSUE THREAD

**Issue by BinaryKhaos** [davidben/nspluginwrapper#29]
Hi.

I haven't used nspluginwrapper in ages but due to the recent lack of a new 64bit flash version, Gentoo "forced" it upon me again. ;-) Unfortunately it did not work out of the box:

nspluginwrapper -v -i /opt/Adobe/flash-player32/plugin/libflashplayer.so 
/usr/lib64/nspluginwrapper/i386/linux/npviewer.bin: relocation error: /usr/lib64/nspluginwrapper/i386/linux/npviewer.bin: symbol _Unwind_GetIPInfo, version GCC_3.0 not defined in file libgcc_s.so.1 with link time reference
/usr/lib64/nspluginwrapper/i386/linux/npviewer.bin: relocation error: /usr/lib64/nspluginwrapper/i386/linux/npviewer.bin: symbol _Unwind_GetIPInfo, version GCC_3.0 not defined in file libgcc_s.so.1 with link time reference
nspluginwrapper: no appropriate viewer found for /opt/Adobe/flash-player32/plugin/libflashplayer.so

_Unwind_GetIPInfo was added @ 4.2.0 and is thus 4.2.0. Changing libgcc_s.Version accordingly fixed the issue for me. Otherwise it was a simple no-go (see above).

Forgot to add: This is with a pretty much up2date "~amd64" Gentoo with gcc-4.4.5 (skipping 4.5.x series and waiting for another 4.6.x release to jump the boat -g-)

**Comment by davidben** [comment]
Ugh. This lsb-build hack really needs to go. (Bug #5)

Does master work now? I'll leave this ticket open until you can confirm the build works.

**Comment by BinaryKhaos** [comment]
Thanks David. Works fine now... or at least as fine as nspluginwrapper ever worked. ;-)
