### ISSUE TITLE
nspluginwrapper-1.4.0 install fails if used parallel make

### ISSUE THREAD

**Issue by garrymar** [davidben/nspluginwrapper#30]
nspluginwrapper-1.4.0 install phase fails when used parallel make in projects like Gentoo. Solution provided in Gentoo bug system http://bugs.gentoo.org/show_bug.cgi?id=368665#c10.

**Comment by davidben** [comment]
Thanks for the heads up! I think the patch is actually a little overzealous in adding the dependency to install.viewer and install.libnoxshm, but I just applied it as-is.

**Comment by chutz** [comment]
Hi, if you look at this Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=371705

Apparently that patch does not work in some configurations, I have created a better one that does away with the need to use install.dirs at all by using install -D so it will create the directories automatically. If knew how to attach something to here I would. A version for 1.4.2 is with the 1.4.2 ebuild in the Gentoo tree.

**Comment by davidben** [comment]
It looks like install -D is a GNU-ism and isn't available on BSD? I know FreeBSD has a package of nspluginwrapper in ports, and I'd rather not make life needlessly complicated for them. I found one instance of install.dirs missed by the earlier patch, so perhaps that resolves the issue? dbce3d441879d73eab0cd21bd4cd17882fa1f789
