### ISSUE TITLE
nspluginwrapper uses overlay?

### ISSUE THREAD

**Issue by skoehler** [davidben/nspluginwrapper#31]
I'm using nspluginwrapper 1.4.2. Running Flash applications work fine. However, if I put a window with a white background over the window with the flash plug-in, that I can see "through" the window, and I can "see" the flash application through the white window.

This remembers me of the "good old times", when a video overlay was basically a rectangle filled with a particular color. And every pixel on the screen with the right color was replaced that has the right color was replaced with the overlay content. Well, it seems nspluginwrapper is using an overlay. However, with a particularly bad color (white).

I remember, that sometimes it affects windows with black background (like my terminal window).

I'm using nvidia's binary driver.

**Comment by davidben** [comment]
Well, nspluginwrapper doesn't use an overlay or anything directly, it just 
forwards along whatever pixmap or window Flash sends. (There is a slight 
indirection with XEmbedding windowed plugins that actually I can probably 
just do away with now. I don't think it could be causing this though.) 
That is odd though. It's conceivable Flash is using one? Or that something 
weird about nspluginwrapper is triggering this. Or maybe even a graphics 
driver or compositor bug.

Does this occur when you use a 32-bit browser running Flash natively?

**Comment by skoehler** [comment]
I disabled the hardware acceleration inside the flash plugin settings. This has fixed it.
At work, the 64bit system doesn't show that behaviour. So I guess, this setting made the difference.

I will try on a 32bit system soon. I think, this might not be related to nspluginwrapper after all.

**Comment by davidben** [comment]
I would expect this to be very dependent on the graphics driver and 
things. You're probably better off testing on a 32-bit browser on the same 
system, otherwise the check doesn't say much. I usually use a Chromium 
nightly or a tarball from Mozilla (both have 32-bit builds and are 
perfectly relocatable, so you can just untar them somewhere. May need to 
set MOZ_PLUGIN_PATH as appropriate).

**Comment by skoehler** [comment]
I downloaded some nightly firefox tarball, 32bit of course, and as soon as I enable the hardware acceleration inside the flash plugin, it seems to use some kind of overlay and shines through other windows. Also tried Opera, 64bit browser, but which comes with its own 32bit plugin container. Same thing.

**Comment by davidben** [comment]
Alright. I guess this is a driver or Flash problem then.
