### ISSUE TITLE
parallel build issue

### ISSUE THREAD

**Issue by gagern** [davidben/nspluginwrapper#32]
Building nspluginwrapper in parallel using `make -j5` or similar has a good chance to fail.

The reason lies here:
https://github.com/davidben/nspluginwrapper/blob/2f2e00a95a21f4c7824964610ad1ca313578dd6c/Makefile#L336
The target `$(LSB_OBJ_DIR)` is responsible for the creation of the required directory. But the `$(LSB_OBJ_DIR)/%.o` target doesn't directly depend on it. Only the order in other dependency lists ensures a correct build under -j1 conditions.

The simplest fix would be changing the prerequisites of the compiler target to this:
`$(LSB_OBJ_DIR)/%.o: $(LSB_SRC_DIR)/%.c $(LSB_OBJ_DIR)`
This will ensure that the target dir exists before any files are to be placed in it.

If you want me to, I can fork, commit that change, and post a pull request, but it's probably not worth the effort.

**Comment by davidben** [comment]
Thanks! Fixed in c5b1faa7d384a76c39256ab1a2d179f26493b48f.
