### ISSUE TITLE
nspluginwrapper removes symlinks to valid plugins on update

### ISSUE THREAD

**Issue by swt2c** [davidben/nspluginwrapper#34]
While investigating issue 33, I found that when 'nspluginwrapper -a -v -u' is run, it removes the symbolic links to the Adobe Reader plugin, leaving the plugin effectively disabled.  I am thinking that the correct behavior might be that nspluginwrapper should probably act on the linked file, not the link itself.

**Comment by davidben** [comment]
What package are you using? The nspluginwrapper tool is a monster. I keep meaning to clean it up but haven't had the time; everyone's got a pile of patches on top (the original tool is bad; the patches are worse), so I don't want to do much without a serious cleanup (bug #4) or I'll make every distribution rebase their patches over and over. Anyway, I'm not aware of any funny logic with symlinks? If you're on Ubuntu or Debian, they _heavily_ patch it to do all kinds of crazy symlink stuff. If you're using that package, you'll want to bother them about it.

If not, what kind of symlinks are you talking about?

**Comment by swt2c** [comment]
You are right, my bad.  I'm on Ubuntu.  I didn't realize the symlinks stuff was added by Debian/Ubuntu.  I'll redirect this issue there.
