### ISSUE TITLE
NSPlugin Viewer crashes

### ISSUE THREAD

**Issue by Niek** [davidben/nspluginwrapper#41]
I am using the webkit-based PhantomJS (https://github.com/ariya/phantomjs) to make screenshots of web pages. Flash content is a bit problematic though, several pages (example: http://www.adobe.com/software/flash/about/) hang the rendering process. I have tried nspluginwrapper 1.2.2 (default Ubuntu) which spawns the following errors:

```
*** NSPlugin Viewer  *** WARNING: unhandled variable 18 (<unknown variable>) in NPN_GetValue()
(process:30321): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.28.6/./gobject/gtype.c:2712: You forgot to call g_type_init()
(process:30321): GLib-CRITICAL **: g_once_init_leave: assertion `initialization_value != 0' failed
(process:30321): Gdk-CRITICAL **: IA__gdk_x11_display_get_xdisplay: assertion `GDK_IS_DISPLAY (display)' failed
*** NSPlugin Viewer  *** WARNING: unhandled variable 18 (<unknown variable>) in NPN_GetValue()
```

Upgrading to nspluginwrapper 1.4.4 (from source) spawns similar errors:

```
(process:29911): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.28.6/./gobject/gtype.c:2712: You forgot to call g_type_init()
(process:29911): GLib-CRITICAL **: g_once_init_leave: assertion `initialization_value != 0' failed
(process:29911): Gdk-CRITICAL **: IA__gdk_x11_display_get_xdisplay: assertion `GDK_IS_DISPLAY (display)' failed
*** NSPlugin Viewer  *** ERROR: rpc_end_sync called when not in sync!
```

Any thoughts? If I can help with a gdb stack trace or more verbose debug messages, let me know.

**Comment by davidben** [comment]
1.2.2 is from before my tenure and contains many many known bugs. You should talk to your distribution about providing more stable packages. But I don't think any of those errors are related here as you get it in 1.4.4 as well.

The error looks like `g_type_init` wasn't called, which I think is generally expected to be the browser's responsibility? Certainly both Chrome and Firefox do so... I can see about calling it in NSPW too if you're allowed to call it twice, but this sounds like a browser bug. What version of Qt do you have? PhantomJS just uses QtWebKit. I see some references in Google about Flash not working in some older versions of Qt because of this same reason. It sounds like it got fixed sometime between 4.4 and 4.6.

(Actually I think this is in the wrapper, not the viewer. Variable 18 is because 1.2.2 doesn't support `NPNVprivateModeBool`. The `rpc_end_sync` error is because viewer shutdown is a little poor right now. I should fix that.)

**Comment by Niek** [comment]
This is on Qt 4.7.2, so the Qt version shouldn't be the issue (unless there are fixes for this in 4.7.3 or the development branch).

I'm not sure if the `rpc_end_sync` error is the cause of the crash, or something else. Reading through the PhantomJS code, I see it only sets `QWebSettings::PluginsEnabled` to true. I think everything else has to be done in webkit.

**Comment by davidben** [comment]
`rpc_end_sync` isn't terribly interesting. Like I said, viewer shutdown works poorly right now when the wrapper is killed.

Can you perhaps attach gdb to your process (where the wrapper lives) and the viewer to get a stack trace? Also setting `NPW_DEBUG=1` will give you a stream of debug info, although I don't think the latter would help in this error. A bug like that is going to fail really early.

I'll see about giving PhantomJS a try myself. I have Qt 4.7.0, so it's probably not a Qt thing then. Perhaps all the browsers with QtWebKit happen to run `g_type_init` and QtWebKit never actually remembers to do so itself. Another thing worth trying is a 32-bit PhantomJS and everything with the usual 32-bit Flash. The Internet suggests it too crashes when `g_type_init` hasn't been called?

**Comment by Niek** [comment]
I did some more digging and found that the `g_type_init` bug was fixed in webkit a year ago: http://trac.webkit.org/changeset/61307 - the fix should be present in Qt 4.7.0, but apparently that isn't the case as the error still comes up.

I will retry soon with debugging enabled and try to find some more information.

**Comment by Niek** [comment]
I just pulled the latest QtWebkit from git, and to my surprise the `g_type_init` errors are gone. The Adobe.com URL listed above loads correctly, and I see no more issues with Flash pages. The only errors that remain are:

```
*** NSPlugin Viewer  *** WARNING: unhandled variable 18 (<unknown variable>) in 
*** NSPlugin Wrapper *** WARNING: unhandled variable 18 in NPP_GetValue()
*** NSPlugin Wrapper *** ERROR: no valid NPP -> PluginInstance mapping found
```

But these doesn't seem to be critical. Closing this issue now, as upgrading to the latest versions fixes the issues.

**Comment by davidben** [comment]
Well, that last one is not so good, but I wouldn't be surprised if it went away on switching to the latest release. The first two are uninteresting and just your distro's ancient version not supporting `NPNVprivateModeBool`.
