### ISSUE TITLE
Update of normal browser plugin make nspluginwrapper loose "wrapped" plugin

### ISSUE THREAD

**Issue by Morganlej** [davidben/nspluginwrapper#47]
I do not know if this is Mageia specific or upstream.
I posted a bug at Magiea bug tracker
And post it here too for advice, and will link to this from Mageia.
https://bugs.mageia.org/show_bug.cgi?id=9053 below:

----------------------8<----------------
Package: nspluginwrapper

Description of problem:
Suddenly my security plugin for Firefox did not work anymore.
I tracked it to an automatic update of flash browser plugin;
Updating flash-player-plugin makes libplugins.so loose the wrapper!
 # nspluginwrapper -l
listed nothing, so i "rewrapped" it again like when i installed it:
 # nspluginwrapper -i /usr/local/lib/personal/libplugins.so
And it is working again. 
The plugin is for BankID, see my HOWTO referenced below

I posted the problem in forum
https://forums.mageia.org/en/viewtopic.php?f=7&t=4386
and doktor5000 replied: Probably a bug with nspluginwrapper, or specifically
with one of the filetriggers /var/lib/rpm/filetriggers/nspluginwrapper.*

Version-Release number: 1.4.4-1.mga2

How reproducible:
Confirmed on another computer with same setup.

Steps to Reproduce:
1. Have elder version flash-player-plugin installed
2. Run nspluginwrapper -i /usr/local/lib/personal/libplugins.so
   I have only tried that plugin, see my HOWTO on Nexus BankID
   https://forums.mageia.org/en/viewtopic.php?f=41&t=4384
   Verify it installed: run nspluginwrapper -l
3. update flash-player-plugin 
   I now have version: 11.2.202.262-1.mga2.nonfree

4) See the plugin is gone by using:  nspluginwrapper -l

(EDITed to avoid bad autoformatting)

**Comment by davidben** [comment]
You're right that nspluginwrapper isn't seeing much activity anymore, at least from me. Adobe has released a 64-bit version of the Flash player, so the most common use case is negated. Certainly I don't have any use for it. (I don't even use Linux anymore.) If you can run the plugin natively, I _strongly_ recommend you not use nspluginwrapper. Both Firefox and Chrome support out-of-process plugins and do so much better. (If you're using some browser that doesn't, consider using a different browser or asking your browser vendor to pick up this feature.)

If your distribution is using nspluginwrapper for 64-bit Flash, _please_ inform them that there is now a native one. You're only adding a source of bugs if you use it. (I started working on nspluginwrapper when I discovered that my frequent Flash crashes were not actually Adobe's fault.)

Anyway, that aside, wrapper management is certainly a mess. I think distributions tended to also patch it though, so you should talk to them. That was the one set of patches I wasn't able to consolidate. I had plans to rework it all (split into a low-level wrapper-making tool for people to write higher-level management tools out of), but that was before 64-bit Flash.

**Comment by Morganlej** [comment]
Thank you for the quick reply :)
But I must explain better: I have 64 bit system, 64 bit firefox, but this proprietary autentication plugin i must use is only available as 32 bit.  It works nicely to use nspluginwrapper for that.

The problem i experience is that when the 64 bit flasplayer plugin get updated, firefox no longer see the autentication plugin until i run nspluginwrapper on it again.

Not a problem when you know it, but normal users have hard to find and correct the problem when he suddenly can no longer log in to is bank...  because of some automatic update of another plugin some days ago.

As I explained in my HOWTO it is possible to use 32 bit firefox on 64 bit system to avoid nspluginwrapper.

**Comment by davidben** [comment]
Mm. Yeah, anything involving automatic updates and the like is probably your distribution's problem. They shouldn't be involving nspluginwrapper at all for Flash anymore.

**Comment by Morganlej** [comment]
Yep looks suspisious.  Wonder what triggers whatever is happening.
Maybe some old handling of flash plugin is still there doing what now is bad things. 
This is far from being my cup of tea and i let the package manager look into it.
I can test of course.
Thank you for your fast and kind replies :)
Closing for now.
